### ISSUE TITLE
Sometimes the ends are white.

### ISSUE THREAD

**Issue by EliteDaMyth** [cyberpirate92/code2img#11]
![](https://cdn.discordapp.com/attachments/653944744145190922/734059869203857489/unknown.png)
sometimes, the image returned isnt complete and has white ends on both sides

**Comment by cyberpirate92** [comment]
Still seems to be happening. Probably a race condition. Reopening issue, needs further investigation.

**Comment by cyberpirate92** [comment]
With 7fcc9dd, this seems to be fixed. Feel free to reopen issue if you encounter this again. Thanks for reporting :)
