### ISSUE TITLE
Customize background Image

### ISSUE THREAD

**Issue by three1bro** [cyberpirate92/code2img#4]
how can i change the img background color, or just remove the bg color

**Comment by cyberpirate92** [comment]
That is not yet available as of now. Will be added soon.

**Comment by cyberpirate92** [comment]
This is added in commit b713babd4d1aae192d65942387795867c864c208.
- To set a image, use `background-image` query parameter and set it's value to a image URL.
- To set a background color use `background-color` query parameter to any valid value for CSS [`background`](https://developer.mozilla.org/en-US/docs/Web/CSS/background) property. 
- To remove background completely, set `show-background` to `false`.

For more information, refer the [API documentation](https://github.com/cyberpirate92/code2img#api-documentation)
